OBJ=cmd_adm_nslookup.o interface.o
SRC=cmd_adm_nslookup.c interface.c

%ifdef GNU
OBJ=$(addprefix $(OBJDIR)/,$(subst .c,.o,$(SRC)))

$(OBJDIR)/%.o: %.c $(OBJDIR)
	$(CC) -I$(OBJDIR) -I.. $(CFLAGS) -o $@ -c $<
%else
.c.o:
	$(CC) $(CFLAGS) -I.. -c $*.c
%endif

all: $(OBJ)
	ar rlcu mudlib.a $(OBJ)

clean:
	-rm -f *.o
	-rm -f mudlib.a

