// Monster file generated by The Monster Maker.
// Comments to: kyricc@knapp38.res.iastate.edu
//
// Created by kyricc@DysfunctionalMUD.
//

#include <mudlib.h>
#include <gender.h>

inherit MONSTER "/human";

void
create()
{
  ::create();

  set_name("ron");
  set_short("Ron Jeremy");
  set_long(@ENDLONG
This is one fat, hairy man!  But don't let is...umm...lack of good looks
fool you.  This man has gotten laid more than most rabbits.
ENDLONG);
}
