.\"determine whether an object can be picked up or not
.TH get 1 "Oct 9 1995" Ultralib ""

.SH NAME
get - determine whether an object can be picked up or not

.SH SYNOPSIS
(boolean) ob->get();

.SH DESCRIPTION
The get() lfun is included in all objects.  get() returns 1 (TRUE) if the
object can be picked up.  If the object cannot be picked up, get() should
return 0 (FALSE).

.SH SEE ALSO
drop(1), clone(6)
