.\"destroy every loaded object on the mud including the master object
.TH junk 6 "Oct 7 1995" Ultralib "Wizard Commands"

.SH NAME
junk - destroy every loaded object on the mud including the master object

.SH SYNOPSIS
junk
junk <arg1, arg2, ... >

.SH DESCRIPTION
This is a bogus command that when invoked destroys every existing object
that is loaded into memory at the time of invocation.  If the command fails,
it will return zero.  Otherwise it will return 1.  If a player or wizard
attempts to invoke this command, the respective player's interactive object
will be destroyed, leaving all other objects untouched.

.SH SEE ALSO
test(5), objects(3), bogus(3)
User's Guide To Bogus Commands and Functions, 1995 MndInc. et. al.
